version: 2.1

jobs:

  test:
    docker:
      - image: circleci/python:3.7-buster
    steps:
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y gnupg2 python3-pyqt5 tor xvfb
      - run:
          name: Start tor service
          command: sudo service tor start
      - checkout
      - run:
          name: Install python dependencies
          command: pipenv install --dev
      - run:
          name: Run tests
          command: pipenv run xvfb-run -s "-screen 0 1280x1024x24" python setup.py pytest

  build-ubuntu-bionic:
    docker:
      - image: ubuntu:18.04
    steps:
      - run:
          name: Install dependencies
          command: |
            apt-get update
            DEBIAN_FRONTEND=noninteractive apt-get install -y git ssh ruby-dev rubygems build-essential fakeroot python-all python3-all dh-python python3-pyqt5 python3-stdeb python3-requests python3-socks python3-packaging python3-dateutil python3-pytest python3-pytest-runner gnupg2
            gem install --no-ri --no-rdoc rake
            gem install --no-ri --no-rdoc package_cloud
      - checkout
      - run:
          name: Create the .deb package
          command: |
            ./install/build_deb.sh
            dpkg -i deb_dist/gpgsync_*.deb
      - run:
          name: Deploy to packagecloud.io
          command: |
            VERSION=$(cat share/version |cut -dv -f2)
            package_cloud push firstlookmedia/code/ubuntu/bionic deb_dist/gpgsync_${VERSION}-1_all.deb
            package_cloud push firstlookmedia/code/ubuntu/bionic deb_dist/gpgsync_${VERSION}-1.dsc

  build-ubuntu-disco:
    docker:
      - image: ubuntu:19.04
    steps:
      - run:
          name: Install dependencies
          command: |
            apt-get update
            DEBIAN_FRONTEND=noninteractive apt-get install -y git ssh ruby-dev rubygems build-essential fakeroot python-all python3-all dh-python python3-pyqt5 python3-stdeb python3-requests python3-socks python3-packaging python3-dateutil python3-pytest python3-pytest-runner gnupg2
            gem install --no-ri --no-rdoc rake
            gem install --no-ri --no-rdoc package_cloud
      - checkout
      - run:
          name: Create the .deb package
          command: |
            ./install/build_deb.sh
            dpkg -i deb_dist/gpgsync_*.deb
      - run:
          name: Deploy to packagecloud.io
          command: |
            VERSION=$(cat share/version |cut -dv -f2)
            package_cloud push firstlookmedia/code/ubuntu/disco deb_dist/gpgsync_${VERSION}-1_all.deb
            package_cloud push firstlookmedia/code/ubuntu/disco deb_dist/gpgsync_${VERSION}-1.dsc

  build-ubuntu-eoan:
    docker:
      - image: ubuntu:19.10
    steps:
      - run:
          name: Install dependencies
          command: |
            apt-get update
            DEBIAN_FRONTEND=noninteractive apt-get install -y git ssh ruby-dev rubygems build-essential fakeroot python-all python3-all dh-python python3-pyqt5 python3-stdeb python3-requests python3-socks python3-packaging python3-dateutil python3-pytest python3-pytest-runner gnupg2
            gem install --no-ri --no-rdoc rake
            gem install --no-ri --no-rdoc package_cloud
      - checkout
      - run:
          name: Create the .deb package
          command: |
            ./install/build_deb.sh
            dpkg -i deb_dist/gpgsync_*.deb
      - run:
          name: Deploy to packagecloud.io
          command: |
            VERSION=$(cat share/version |cut -dv -f2)
            package_cloud push firstlookmedia/code/ubuntu/eoan deb_dist/gpgsync_${VERSION}-1_all.deb
            package_cloud push firstlookmedia/code/ubuntu/eoan deb_dist/gpgsync_${VERSION}-1.dsc

workflows:
  version: 2
  test:
    jobs:
      - test
  - build-tags:
    jobs:
      - build-ubuntu-bionic:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - build-ubuntu-disco:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - build-ubuntu-eoan:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
