version: 2.1

jobs:

  test:
    docker:
      - image: circleci/python:3.8-buster
    steps:
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y gnupg2 tor xvfb
      - run:
          name: Start tor service
          command: sudo service tor start
      - checkout
      - run:
          name: Install python dependencies
          command: poetry install
      - run:
          name: Run tests
          command: poetry run xvfb-run -s "-screen 0 1280x1024x24" python setup.py pytest

  build-ubuntu-focal:
    docker:
      - image: ubuntu:20.04
    steps:
      - run:
          name: Install dependencies
          command: |
            apt-get update
            DEBIAN_FRONTEND=noninteractive apt-get install -y git ssh ruby-dev rubygems build-essential fakeroot python-all dh-python python3-pytest python3-pytest-runner python3-stdeb python3-pyside2.qtcore python3-pyside2.qtwidgets python3-pyside2.qtgui python3-requests python3-socks python3-packaging python3-dateutil gnupg2
            gem install -N rake
            gem install -N package_cloud
      - checkout
      - run:
          name: Create the .deb package
          command: |
            ./install/build_deb.sh
            dpkg -i deb_dist/gpgsync_*.deb
      - run:
          name: Deploy to packagecloud.io
          command: |
            VERSION=$(cat share/version |cut -dv -f2)
            package_cloud push firstlookmedia/code/ubuntu/focal deb_dist/gpgsync_${VERSION}-1_all.deb
            package_cloud push firstlookmedia/code/ubuntu/focal deb_dist/gpgsync_${VERSION}-1.dsc

  build-ubuntu-groovy:
    docker:
      - image: ubuntu:20.10
    steps:
      - run:
          name: Install dependencies
          command: |
            apt-get update
            DEBIAN_FRONTEND=noninteractive apt-get install -y git ssh ruby-dev rubygems build-essential fakeroot python-all dh-python python3-pytest python3-pytest-runner python3-stdeb python3-pyside2.qtcore python3-pyside2.qtwidgets python3-pyside2.qtgui python3-requests python3-socks python3-packaging python3-dateutil gnupg2
            gem install -N rake
            gem install -N package_cloud
      - checkout
      - run:
          name: Create the .deb package
          command: |
            ./install/build_deb.sh
            dpkg -i deb_dist/gpgsync_*.deb
      - run:
          name: Deploy to packagecloud.io
          command: |
            VERSION=$(cat share/version |cut -dv -f2)
            package_cloud push firstlookmedia/code/ubuntu/groovy deb_dist/gpgsync_${VERSION}-1_all.deb
            package_cloud push firstlookmedia/code/ubuntu/groovy deb_dist/gpgsync_${VERSION}-1.dsc

  build-debian-buster:
    docker:
      - image: debian:buster
    steps:
      - run:
          name: Install dependencies
          command: |
            apt-get update
            DEBIAN_FRONTEND=noninteractive apt-get install -y git ssh ruby-dev rubygems build-essential fakeroot python-all dh-python python3-pytest python3-pytest-runner python3-stdeb python3-pyside2.qtcore python3-pyside2.qtwidgets python3-pyside2.qtgui python3-requests python3-socks python3-packaging python3-dateutil gnupg2
            gem install --no-ri --no-rdoc rake
            gem install --no-ri --no-rdoc package_cloud
      - checkout
      - run:
          name: Create the .deb package
          command: |
            ./install/build_deb.sh
            dpkg -i deb_dist/gpgsync_*.deb
      - run:
          name: Deploy to packagecloud.io
          command: |
            VERSION=$(cat share/version |cut -dv -f2)
            package_cloud push firstlookmedia/code/debian/buster deb_dist/gpgsync_${VERSION}-1_all.deb
            package_cloud push firstlookmedia/code/debian/buster deb_dist/gpgsync_${VERSION}-1.dsc

  build-debian-bullseye:
    docker:
      - image: debian:bullseye
    steps:
      - run:
          name: Install dependencies
          command: |
            apt-get update
            DEBIAN_FRONTEND=noninteractive apt-get install -y git ssh ruby-dev rubygems build-essential fakeroot python-all dh-python python3-pytest python3-pytest-runner python3-stdeb python3-pyside2.qtcore python3-pyside2.qtwidgets python3-pyside2.qtgui python3-requests python3-socks python3-packaging python3-dateutil gnupg2
            gem install -N rake
            gem install -N package_cloud
      - checkout
      - run:
          name: Create the .deb package
          command: |
            ./install/build_deb.sh
            dpkg -i deb_dist/gpgsync_*.deb
      - run:
          name: Deploy to packagecloud.io
          command: |
            VERSION=$(cat share/version |cut -dv -f2)
            package_cloud push firstlookmedia/code/debian/bullseye deb_dist/gpgsync_${VERSION}-1_all.deb
            package_cloud push firstlookmedia/code/debian/bullseye deb_dist/gpgsync_${VERSION}-1.dsc

  build-fedora-31:
    docker:
      - image: fedora:31
    steps:
      - run:
          name: Install dependencies
          command: |
            dnf install -y git openssh ruby-devel make automake gcc gcc-c++ rpm-build python3-pytest-runner python3-pyside2 python3-requests python3-packaging python3-dateutil gnupg2
            gem install package_cloud
      - checkout
      - run:
          name: Create the .rpm package
          command: |
            ./install/build_rpm.sh
            dnf install -y dist/gpgsync-*-1.noarch.rpm
      - run:
          name: Deploy to packagecloud.io
          command: |
            VERSION=$(cat share/version |cut -dv -f2)
            package_cloud push firstlookmedia/code/fedora/31 dist/gpgsync-${VERSION}-1.noarch.rpm
            package_cloud push firstlookmedia/code/fedora/31 dist/gpgsync-${VERSION}-1.src.rpm

  build-fedora-32:
    docker:
      - image: fedora:32
    steps:
      - run:
          name: Install dependencies
          command: |
            dnf install -y git openssh ruby-devel make automake gcc gcc-c++ rpm-build python3-pytest-runner python3-pyside2 python3-requests python3-packaging python3-dateutil gnupg2
            gem install package_cloud
      - checkout
      - run:
          name: Create the .rpm package
          command: |
            ./install/build_rpm.sh
            dnf install -y dist/gpgsync-*-1.noarch.rpm
      - run:
          name: Deploy to packagecloud.io
          command: |
            VERSION=$(cat share/version |cut -dv -f2)
            package_cloud push firstlookmedia/code/fedora/32 dist/gpgsync-${VERSION}-1.noarch.rpm
            package_cloud push firstlookmedia/code/fedora/32 dist/gpgsync-${VERSION}-1.src.rpm

build-fedora-33:
    docker:
      - image: fedora:33
    steps:
      - run:
          name: Install dependencies
          command: |
            dnf install -y git openssh ruby-devel make automake gcc gcc-c++ rpm-build python3-pytest-runner python3-pyside2 python3-requests python3-packaging python3-dateutil gnupg2
            gem install package_cloud
      - checkout
      - run:
          name: Create the .rpm package
          command: |
            ./install/build_rpm.sh
            dnf install -y dist/gpgsync-*-1.noarch.rpm
      - run:
          name: Deploy to packagecloud.io
          command: |
            VERSION=$(cat share/version |cut -dv -f2)
            package_cloud push firstlookmedia/code/fedora/33 dist/gpgsync-${VERSION}-1.noarch.rpm
            package_cloud push firstlookmedia/code/fedora/33 dist/gpgsync-${VERSION}-1.src.rpm


workflows:
  version: 2
  test:
    jobs:
      - test
  build-tags:
    jobs:
      - build-ubuntu-focal:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      # - build-ubuntu-groovy:
      #     filters:
      #       tags:
      #         only: /^v.*/
      #       branches:
      #         ignore: /.*/
      - build-debian-buster:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - build-debian-bullseye:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - build-fedora-31:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - build-fedora-32:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      # - build-fedora-33:
      #     filters:
      #       tags:
      #         only: /^v.*/
      #       branches:
      #         ignore: /.*/
