workflows:
  version: 2
  test:
    jobs:
      - test
version: 2
jobs:
  test:
    environment:
      FLM_ENV: "test"
    docker:
      - image: circleci/python:3.7.5-buster
    steps:
      - run:
          name: Install dependencies
          command: |
            apt-get update
            apt-get install -y gnupg2 python3-pyqt5 tor
      - run:
          name: Restart tor service
          command: service tor restart
      - checkout
      - run:
          name: Install python dependencies
          command: pipenv install --dev
      - run:
          name: Run tests
          command: pipenv run python setup.py pytest
