workflows:
  version: 2
  test:
    jobs:
      - test
version: 2
jobs:
  test:
    environment:
      FLM_ENV: "test"
    docker:
      - image: circleci/python:3.7-buster
    steps:
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y gnupg2 python3-pyqt5 tor xvfb
      - run:
          name: start tor service
          command: sudo service tor start
      - checkout
      - run:
          name: Install python dependencies
          command: pipenv install --dev
      - run:
          name: Run tests
          command: pipenv run xvfb-run -s "-screen 0 1280x1024x24" python setup.py pytest
